import {
  AppstoreOutlined,
  BankOutlined,
  CloudOutlined,
  CopyOutlined,
  CreditCardOutlined,
  DatabaseOutlined,
  DownOutlined,
  EuroOutlined,
  FileAddOutlined,
  FireOutlined,
  FormOutlined,
  HomeOutlined,
  InfoOutlined,
  LaptopOutlined,
  LoginOutlined,
  MailOutlined,
  MenuFoldOutlined,
  RedditOutlined,
  RobotOutlined,
  ScanOutlined,
  SearchOutlined,
  SettingOutlined,
  ShoppingCartOutlined,
  ShoppingOutlined,
  SolutionOutlined,
  SwapOutlined,
  TrophyOutlined,
  UserOutlined,
  UsergroupAddOutlined,
} from '@ant-design/icons';

const iconSize = 20;

export const icon_lib = {
  menu: <MenuFoldOutlined style={{ fontSize: iconSize }} />,
  createNew: <FileAddOutlined style={{ fontSize: iconSize }} />,
  home: <HomeOutlined style={{ fontSize: iconSize }} />,
  company: <BankOutlined style={{ fontSize: iconSize }} />,
  business: <EuroOutlined style={{ fontSize: iconSize }} />,
  employee: <UsergroupAddOutlined style={{ fontSize: iconSize }} />,
  product: <ShoppingOutlined style={{ fontSize: iconSize }} />,
  warehouse: <DatabaseOutlined style={{ fontSize: iconSize }} />,
  app: <AppstoreOutlined style={{ fontSize: iconSize }} />,
  device: <LaptopOutlined style={{ fontSize: iconSize }} />,
  asset: <CloudOutlined style={{ fontSize: iconSize }} />,
  setting: <SettingOutlined style={{ fontSize: iconSize }} />,
  mail: <MailOutlined style={{ fontSize: iconSize }} />,
  avatar: <UserOutlined style={{ fontSize: iconSize }} />,
  search: <SearchOutlined style={{ fontSize: iconSize }} />,
  login: <LoginOutlined style={{ fontSize: iconSize }} />,
  dropDown: <DownOutlined style={{ fontSize: iconSize }} />,
  scan: <ScanOutlined style={{ fontSize: iconSize }} />,
  modify: <FormOutlined style={{ fontSize: iconSize }} />,
  swap: <SwapOutlined style={{ fontSize: iconSize }} />,
  report: <TrophyOutlined style={{ fontSize: iconSize }} />,
  utilities: <RobotOutlined style={{ fontSize: iconSize }} />,
  mission: <SolutionOutlined style={{ fontSize: iconSize }} />,
  sales: <ShoppingCartOutlined style={{ fontSize: iconSize }} />,
  marketing: <FireOutlined style={{ fontSize: iconSize }} />,
  accounting: <CreditCardOutlined style={{ fontSize: iconSize }} />,
  support: <RedditOutlined style={{ fontSize: iconSize }} />,
  information: <InfoOutlined style={{ fontSize: iconSize }} />,
  copy: <CopyOutlined style={{ fontSize: iconSize }} />,
};
